version: 2
updates:
  # 1. npm 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-deps:
        patterns:
          - "*"
        dependency-type: "production"

  # 2. GitHub Actions 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 3. Docker 
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
