# Generated by Django 5.0.9 on 2026-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('tattoo_size', models.CharField(blank=True, max_length=100, verbose_name='tamanho da tatuagem')),
                ('description', models.TextField(verbose_name='descrição')),
                ('suggested_date', models.DateTimeField(verbose_name='data/hora sugerida')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'solicitação de orçamento',
                'verbose_name_plural': 'solicitações de orçamento',
                'ordering': ('-created_at',),
            },
        ),
    ]
