variable "location" {
  type        = string
  default     = "canadacentral"
  description = "Azure region for most resources. Must be one of the regions your subscription is actually allowed to deploy to — new/student subscriptions get a restricted list (Subscriptions > your sub > Settings > Policies in the portal shows it) until Azure's activation review clears; canadacentral was confirmed allowed for this subscription."
}

variable "db_location" {
  type        = string
  default     = "southafricanorth"
  description = "Azure region for the MySQL Flexible Server specifically. Separate from 'location' because MySQL Flexible Server SKU capacity isn't available in every allowed region for every subscription — check with 'az mysql flexible-server list-skus -l <region>' if you need to change this."
}

variable "project_name" {
  type        = string
  default     = "yara-tattoo"
  description = "Used as a prefix for all named resources."
}

variable "github_owner" {
  type        = string
  description = "GitHub owner/organization (e.g. 'nncl')."
}

variable "github_repo" {
  type        = string
  description = "GitHub repository name (e.g. 'Univesp-PI-I')."
}

variable "github_branch" {
  type        = string
  default     = "main"
  description = "Branch allowed to assume the GitHub Actions deploy identity via OIDC."
}

# --- Container images (GitHub Container Registry) ---------------------------
#
# There's no backend/frontend_image_tag variable: Container Apps are created
# with a public placeholder image (see container_apps.tf) and Terraform is
# told to stop tracking the image field afterward. The real image is owned
# by the GitHub Actions deploy workflow (`az containerapp update --image`)
# from then on, so re-running `terraform apply` won't revert a live deploy.
#
# No ghcr_username/ghcr_token variables: the images are public on GHCR, so
# Container Apps pulls them with no credential. (This also happens to
# sidestep a confirmed bug where this environment's Container Apps
# `registries` field never persists — see container_apps.tf.)

# --- Compute ------------------------------------------------------------------

variable "container_cpu" {
  type        = number
  default     = 0.25
  description = "vCPU allocated per container (Container Apps billing unit)."
}

variable "container_memory" {
  type        = string
  default     = "0.5Gi"
  description = "Memory allocated per container."
}

# --- Database -------------------------------------------------------------

variable "db_sku_name" {
  type        = string
  default     = "B_Standard_B1ms"
  description = "MySQL Flexible Server SKU. B_Standard_B1ms is the cheapest Burstable tier."
}

variable "db_storage_gb" {
  type        = number
  default     = 20
  description = "MySQL Flexible Server storage in GB (20 is the minimum)."
}

variable "db_name" {
  type        = string
  default     = "tattoo"
  description = "MySQL initial database name."
}

variable "db_username" {
  type        = string
  default     = "tattoo"
  description = "MySQL admin username (password is auto-generated by Terraform)."
}

variable "my_ip_address" {
  type        = string
  default     = null
  description = "Optional: your current public IP, to allow connecting to MySQL directly from your laptop (e.g. with a MySQL client) for debugging. Leave null to skip."
}

# --- Application secrets ----------------------------------------------------

variable "django_admin_email" {
  type        = string
  default     = "admin@example.com"
  description = "Non-sensitive admin email shown in Django."
}

variable "django_admin_username" {
  type        = string
  sensitive   = true
  description = "Django superuser username created on first boot."
}

variable "django_admin_password" {
  type        = string
  sensitive   = true
  description = "Django superuser password created on first boot."
}
